# Generated by Django 4.2.4 on 2023-09-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_description',
            field=models.FloatField(default=0.0),
        ),
    ]
